### ISSUE TITLE
[BUG]Disc-InventoryHUD

### ISSUE THREAD

**Issue by Mastercuts20** [DiscworldZA/gta-resources#232] opened 2019-12-07 07:07 UTC
i get this error (attached) when i try and load into my server while its downloading and wont move on
thanks in advance - mastercuts20
![image](https://user-images.githubusercontent.com/34855510/70370537-42de5d00-1918-11ea-81ce-97d52491727b.png)

**Comment by rex2630** [comment] 2019-12-07 21:09
Thats not issue of the script. Either u did something wrong or FiveM servers was off or either your invernet speed of pc or server is slow. Nothing to do about. Clear cache on both sides, that should help. Script is functional for everyone else, so this is not a bug. If u dont get it working try the discord. Im closing this issue

**Closed by rex2630** 2019-12-07 21:09 UTC
Labels: bug
